- name: Install Apache
  yum:
    name: httpd
    state: latest
- name: Create a default page
  shell: echo "<h1>Hello world from EC2 Image Builder and Ansible</h1>" > /var/www/html/index.html
- name: Enable Apache
  service:
    name: httpd
    enabled: yes
    state: started
