- name: Install related packages.
  yum:
    name: '{{ item }}'
    state: present
    lock_timeout: 180
  with_items:
    - MySQL-python
    - libselinux-python
    - yum-utils

- name: Install release
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
    state: present
    lock_timeout: 180

# TODO: 整理する
- name: Install MySQL
  yum:
    name: '{{ item }}'
    state: present
    lock_timeout: 180
  with_items:
    - mysql-community-server
    - mysql-community-client
    - mysql-community-common
    - mysql-community-libs
    - gcc
    - redhat-rpm-config
    - mysql
    - mysql-devel
    - ruby-devel
